#!/usr/bin/env perl
use strict;

sub print_def {
	my $name = shift;
	my $base = shift;
	my @decls = @_;
	my @names = ();
	foreach my $decl (@decls) {
		my $name = $decl;
		$name =~ s/\s*=.*$//;
		$name =~ s/^.* ([A-Za-z0-9_]+)$/\1/;
		push @names, $name;
	}

	my $base = "$base<" . join(", ", @names) . ">";

	print "\ttemplate< " . join(", ", @decls) . " >\n\tclass $name: public $base {\n\tpublic:\n\t\t$name(): $base() {}\n";

	for (my $args = 1; $args <= 3; ++$args) {
		my @l = (); my @v = ();
		for (my $i = 1; $i <= $args; ++$i) { push @l, "Arg$i"; push @v, "arg$i"; }
		print "\n\t\ttemplate<" . join(", ", map { "class $_" } @l) . ">\n";
		print "\t\t$name(" . join(", ", map { "$l[$_] $v[$_]" } (0..$#l)) . "): $base(" . join(", ", @v) . ") {}\n";
	}

	print "\t};\n\n";
}

print <<EOF;
/*
 * This file is autogenerated; do not edit.
 * Modify tools/mkstl.pl and regenerate the file if you need to.
 */
#ifndef PIRE_COMPAT_H_INCLUDED
#define PIRE_COMPAT_H_INCLUDED

#include <string>
#include <vector>
#include <deque>
#include <list>
#include <map>
#include <set>
#include <bitset>
#include <utility>
#include <memory>
#include <iostream>
#include <algorithm>
#include <stdexcept>
#include <iterator>
#include <functional>
#include <assert.h>

#ifdef PIRE_CHECKED
#define YASSERT(e) assert(e)
#else
#define YASSERT(e)
#endif

namespace Pire {
EOF

print_def 'yvector',   'std::vector',    'class T', 'class A = std::allocator<T>';
print_def 'ydeque',    'std::deque',     'class T', 'class A = std::allocator<T>';
print_def 'ylist',     'std::list',      'class T', 'class A = std::allocator<T>';
print_def 'ymap',      'std::map',       'class K', 'class V', 'class C = std::less<K>', 'class A = std::allocator< std::pair<K, V> >';
print_def 'yset',      'std::set',       'class T', 'class C = std::less<T>', 'class A = std::allocator<T>';

print_def 'yauto_ptr', 'std::auto_ptr',  'class T';
print_def 'ybitset',   'std::bitset',    'size_t N';
print_def 'ypair',     'std::pair',      'class A', 'class B';

print_def 'ybinary_function', 'std::binary_function', 'class A', 'class B', 'class R';

print <<EOF;
	typedef std::string ystring;
	typedef std::istream yistream;
	typedef std::ostream yostream;

	template<class A, class B>
	inline ypair<A, B> ymake_pair(A a, B b) { return ypair<A, B>(a, b); }

	template<class T>
	inline const T& ymin(const T& a, const T& b) { return std::min(a, b); }

	template<class T>
	inline const T& ymax(const T& a, const T& b) { return std::max(a, b); }

	static std::ostream& Cdbg = std::clog;

	inline yostream& Endl(yostream& s) { return std::endl(s); }

	template<class T>
	static inline void DoSwap(T& a, T& b) { std::swap(a, b); }

	template<class Iter, class T>
	static inline void Fill(Iter begin, Iter end, T t) { std::fill(begin, end, t); }
	
	template <class I, class T, class C>
	static inline I LowerBound(I f, I l, const T& v, C c) {
		return std::lower_bound(f, l, v, c);
	}

	class Error: public std::runtime_error {
	public:
		Error(const char* msg): std::runtime_error(msg) {}
		Error(const ystring& msg): std::runtime_error(msg) {}
	};
}

#endif
EOF


